/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TrackService } from "../track.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TrackCreateInput } from "./TrackCreateInput";
import { Track } from "./Track";
import { TrackFindManyArgs } from "./TrackFindManyArgs";
import { TrackWhereUniqueInput } from "./TrackWhereUniqueInput";
import { TrackUpdateInput } from "./TrackUpdateInput";
import { PlaylistTrackFindManyArgs } from "../../playlistTrack/base/PlaylistTrackFindManyArgs";
import { PlaylistTrack } from "../../playlistTrack/base/PlaylistTrack";
import { PlaylistTrackWhereUniqueInput } from "../../playlistTrack/base/PlaylistTrackWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TrackControllerBase {
  constructor(
    protected readonly service: TrackService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Track })
  @nestAccessControl.UseRoles({
    resource: "Track",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTrack(@common.Body() data: TrackCreateInput): Promise<Track> {
    return await this.service.createTrack({
      data: data,
      select: {
        album: true,
        artist: true,
        createdAt: true,
        genre: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Track] })
  @ApiNestedQuery(TrackFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Track",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async tracks(@common.Req() request: Request): Promise<Track[]> {
    const args = plainToClass(TrackFindManyArgs, request.query);
    return this.service.tracks({
      ...args,
      select: {
        album: true,
        artist: true,
        createdAt: true,
        genre: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Track })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Track",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async track(
    @common.Param() params: TrackWhereUniqueInput
  ): Promise<Track | null> {
    const result = await this.service.track({
      where: params,
      select: {
        album: true,
        artist: true,
        createdAt: true,
        genre: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Track })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Track",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTrack(
    @common.Param() params: TrackWhereUniqueInput,
    @common.Body() data: TrackUpdateInput
  ): Promise<Track | null> {
    try {
      return await this.service.updateTrack({
        where: params,
        data: data,
        select: {
          album: true,
          artist: true,
          createdAt: true,
          genre: true,
          id: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Track })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Track",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTrack(
    @common.Param() params: TrackWhereUniqueInput
  ): Promise<Track | null> {
    try {
      return await this.service.deleteTrack({
        where: params,
        select: {
          album: true,
          artist: true,
          createdAt: true,
          genre: true,
          id: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/playlistTracks")
  @ApiNestedQuery(PlaylistTrackFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PlaylistTrack",
    action: "read",
    possession: "any",
  })
  async findPlaylistTracks(
    @common.Req() request: Request,
    @common.Param() params: TrackWhereUniqueInput
  ): Promise<PlaylistTrack[]> {
    const query = plainToClass(PlaylistTrackFindManyArgs, request.query);
    const results = await this.service.findPlaylistTracks(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        playlist: {
          select: {
            id: true,
          },
        },

        track: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/playlistTracks")
  @nestAccessControl.UseRoles({
    resource: "Track",
    action: "update",
    possession: "any",
  })
  async connectPlaylistTracks(
    @common.Param() params: TrackWhereUniqueInput,
    @common.Body() body: PlaylistTrackWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      playlistTracks: {
        connect: body,
      },
    };
    await this.service.updateTrack({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/playlistTracks")
  @nestAccessControl.UseRoles({
    resource: "Track",
    action: "update",
    possession: "any",
  })
  async updatePlaylistTracks(
    @common.Param() params: TrackWhereUniqueInput,
    @common.Body() body: PlaylistTrackWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      playlistTracks: {
        set: body,
      },
    };
    await this.service.updateTrack({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/playlistTracks")
  @nestAccessControl.UseRoles({
    resource: "Track",
    action: "update",
    possession: "any",
  })
  async disconnectPlaylistTracks(
    @common.Param() params: TrackWhereUniqueInput,
    @common.Body() body: PlaylistTrackWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      playlistTracks: {
        disconnect: body,
      },
    };
    await this.service.updateTrack({
      where: params,
      data,
      select: { id: true },
    });
  }
}
